In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedShuffleSplit

IMPORTING DATASETS

In [2]:
data_log2 = pd.read_pickle('data_log2_Lisbon_Coimbra_threshold.pkl')

In [3]:
data_log2

Protein.Group,A0A0A0MS15,A0A0B4J1X8,A0A0C4DH38,O00391,O00533,O14498,O14594,O14773,O15394,O43505,...,Q9NRN5,Q9NT99,Q9P121,Q9P2S2,Q9UBP4,Q9UBX5,Q9ULB1,Q9Y4C0,Q9Y646,Q9Y6R7
LIS090,7.524839,9.440618,7.131415,6.264067,8.355800,6.222868,5.798631,5.355221,7.860578,9.961581,...,4.881704,6.206844,8.309122,6.827273,10.918669,6.753711,7.058630,7.842011,5.686817,8.661849
LIS098,7.791541,10.339338,7.438942,5.908674,7.962676,5.939913,5.244541,5.406958,7.345982,10.132975,...,4.443076,5.911802,8.087309,6.454133,10.520913,6.709801,6.675844,7.766999,5.921993,7.172317
LIS017,6.309827,10.338246,6.398735,5.907285,8.112664,5.983963,6.077408,5.565893,7.673055,10.326800,...,5.340762,5.799201,8.334036,6.557727,10.662704,7.273665,6.746998,7.561639,6.478499,6.753203
LIS007,9.705954,11.126569,8.909980,6.499706,7.305670,6.535481,4.455360,5.277166,7.376681,9.405173,...,4.832850,5.664161,7.650348,6.108621,10.128703,6.935637,6.173705,6.919900,6.039838,8.260840
LIS026,8.114325,11.020813,8.179367,6.765097,8.106155,5.791983,5.600198,5.660937,7.862365,9.843741,...,5.365864,5.873333,8.227313,6.172213,10.573581,7.251549,6.740347,7.526218,5.885477,7.837615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109089,8.077537,10.276252,6.114536,6.263756,8.592278,6.632142,5.617401,3.798185,7.627045,10.475673,...,4.746759,5.820802,8.031175,6.308907,11.535426,6.661593,6.838952,7.384663,5.610963,8.048367
103176,7.166143,9.615435,6.836252,5.507424,8.735336,6.767973,6.649041,4.822174,7.817770,10.861289,...,4.078755,5.786654,8.127499,6.688908,11.910107,7.323802,6.889108,7.403089,6.744659,7.426063
102357,7.540244,9.095864,6.917348,6.168650,8.682271,6.479260,6.619081,4.656674,7.842086,10.577948,...,3.872740,5.898842,8.187308,6.619353,11.328832,6.578694,6.974518,7.468730,5.825379,7.680205
107362,6.883413,8.918684,6.115443,5.905714,8.505625,5.880857,6.616853,4.357334,7.870044,10.711813,...,4.641332,6.335894,8.406277,6.488221,11.888595,6.983108,6.811664,7.398692,5.688082,7.774392
109522,6.652773,9.735722,6.582636,6.740266,8.526057,6.889145,6.381015,4.882345,7.936449,10.792375,...,5.115212,5.932930,8.254117,6.109064,11.014488,6.811343,6.878725,7.142403,6.194859,7.970330

In [4]:
import pickle

with open('list_groups_LC.pkl', 'rb') as f:
    list_groups = pickle.load(f)

print(list_groups)

['MCI-AD', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-CT', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD', 'MCI-AD']

In [5]:
list_groups = pd.Series(list_groups)

In [6]:
df_all_data = pd.read_pickle('df_all_data_Lisbon_Coimbra_threshold.pkl')
df_Coimbra = df_all_data[df_all_data['Lab_name'] == 'Coimbra']
y_Coimbra = df_Coimbra['Groups']
df_Lisbon = df_all_data[df_all_data['Lab_name'] == 'Lisbon']
y_Lisbon = df_Lisbon['Groups']
cols_to_drop = ['Lab', 'Sample code', 'Groups', 'Age', 'Gender', 'Lab_name']
df_coimbra_dc = df_Coimbra.drop(columns=cols_to_drop)
df_Lisbon_dc = df_Lisbon.drop(columns=cols_to_drop)
print("Same features:", all(df_coimbra_dc.columns == df_Lisbon_dc.columns))

Same features: True

In [7]:
df_coimbra_dc

,A0A0A0MS15,A0A0B4J1X8,A0A0C4DH38,O00391,O00533,O14498,O14594,O14773,O15394,O43505,...,Q9NRN5,Q9NT99,Q9P121,Q9P2S2,Q9UBP4,Q9UBX5,Q9ULB1,Q9Y4C0,Q9Y646,Q9Y6R7
74,5.338670,9.311739,5.368342,6.363451,8.811500,6.429840,6.232016,4.855457,7.661486,10.622482,...,4.850699,5.800033,8.415112,6.759808,11.329084,6.049101,6.976387,7.458193,6.139852,6.967906
75,6.571228,8.986320,5.400070,6.237011,8.556280,6.324377,6.199996,5.496839,7.435754,10.552957,...,4.335769,6.067658,8.203358,6.722548,11.352380,6.357804,6.761179,7.385923,6.398954,7.078834
76,6.168520,9.322539,6.493969,6.427135,9.248172,6.311663,6.820753,4.914124,7.922674,10.808787,...,4.894512,6.021373,8.712379,6.741656,11.591747,6.424029,7.325251,7.835930,6.582637,7.505629
77,7.464734,9.812152,7.210827,6.346462,8.885913,6.343495,6.712692,4.947535,7.917599,10.542935,...,5.383113,5.548655,8.368140,6.500428,11.666797,6.222213,6.355367,7.287186,6.226406,6.764420
78,5.200661,9.718603,6.962723,6.468935,9.069160,6.454995,6.894854,4.204978,7.255576,10.664821,...,5.042412,6.015781,8.467292,6.067114,11.768011,6.594716,7.064355,7.343239,6.230420,7.659339
79,6.080417,9.116656,6.068385,5.989673,8.741073,6.376876,6.712912,4.492783,7.202143,10.756181,...,4.639875,5.923705,8.565658,6.868131,11.799646,6.323964,7.183040,7.686171,6.173755,7.017710
80,6.452478,9.069530,6.511220,6.452959,8.528989,6.739443,6.402576,4.868494,7.410222,10.681379,...,4.933927,6.038425,8.317399,6.656554,11.519843,6.304646,6.712032,7.335998,6.424015,7.993810
81,6.248379,9.583534,6.165206,6.264426,8.599954,6.677551,6.555058,5.721783,7.761059,10.735488,...,5.188793,6.080809,8.294180,6.557016,11.373409,5.980238,6.957938,7.421526,6.570718,8.275324
82,6.457701,9.630560,6.603267,6.517710,9.056933,6.868230,6.649946,4.766001,7.737261,10.769706,...,4.754866,6.008901,8.469768,6.735170,11.248604,6.273708,6.913189,7.510329,5.884200,6.478033
83,4.231041,8.628099,4.587497,5.716072,9.127873,6.015469,7.389291,4.926962,7.582466,10.892209,...,4.915449,6.230405,8.384715,6.565285,11.583666,6.443028,7.160134,7.625658,6.226703,6.323552
84,5.980601,9.876904,5.734991,6.733178,8.633951,6.650305,7.018067,5.690266,7.716717,10.886771,...,5.095979,6.185327,8.603560,6.698705,11.478663,6.437264,7.002736,7.671923,6.349395,7.281457
85,7.312810,9.753976,6.611529,6.319835,9.044648,6.636443,7.089519,5.356809,8.065675,10.829992,...,4.995245,6.035164,8.659439,6.715097,11.325052,6.318846,7.206878,7.879007,6.216154,7.750908
86,4.547986,8.043831,5.804286,6.441137,8.785099,6.588700,7.254311,5.454110,7.497900,10.578373,...,5.173279,6.042358,8.117482,6.452671,11.220644,6.113557,6.671407,7.533657,6.302431,7.850574
88,5.222267,9.327461,5.454232,6.039546,8.897972,6.896114,7.229569,4.578818,7.613760,10.935202,...,4.879951,6.165795,8.691967,6.721632,11.672673,6.266116,6.848948,7.694344,6.537878,6.456325
89,6.128005,9.608436,5.447662,7.167810,8.593914,6.985022,6.485002,5.802731,8.048580,10.664047,...,5.433520,6.655810,8.564020,6.590930,11.381051,6.947760,6.994218,7.577164,6.524509,8.408202
90,5.734769,8.075506,5.033079,6.368910,8.766661,6.726436,6.434321,4.737195,7.740327,10.512286,...,4.493993,6.062817,8.601377,6.750968,11.372267,6.674150,6.948239,7.506542,6.484536,6.379964
91,4.903636,8.586164,5.376527,6.706185,8.946357,6.675322,6.691995,5.199107,8.021208,10.524130,...,4.902479,6.399311,8.283413,6.571254,11.471381,6.363357,6.785838,7.460661,5.912674,6.449895
92,6.501156,9.000558,6.155316,6.395668,8.669222,5.679711,6.197608,4.677925,7.345742,10.321579,...,4.886931,6.015130,8.107625,6.614683,10.935585,6.341632,6.505024,7.415404,6.113988,6.731984
93,7.377948,9.955157,7.287168,6.168341,9.134675,6.632969,7.106453,5.332117,7.802407,10.708351,...,4.981264,6.556210,8.232253,6.536236,11.499716,6.827184,6.834256,7.674976,6.634587,6.897083
94,6.656382,9.102180,6.463307,6.411009,8.588775,6.279436,6.361351,5.236642,7.587800,10.585704,...,4.604220,5.804973,8.025655,6.458802,11.332120,5.541230,6.919388,7.405363,5.858568,7.448092
95,8.077184,9.363833,6.990773,6.547424,8.568032,6.039623,6.348857,4.818559,7.695660,10.406109,...,4.876188,6.045336,7.801107,6.028841,11.030757,7.118069,6.612460,7.339048,6.318971,7.572950
96,5.936742,9.377132,6.318277,6.862067,8.750841,7.083245,6.452806,5.572935,7.756930,10.502792,...,5.665913,5.959295,8.390104,6.181321,11.256392,6.608267,6.567734,7.395354,6.486954,7.461864
97,7.690689,9.165372,6.578625,6.348841,8.376173,6.606812,6.127270,4.942716,7.370844,10.513234,...,4.967588,5.962072,8.207312,6.375823,10.766868,5.983308,6.593481,7.233380,6.215203,6.528526
98,5.675381,9.239462,6.213653,6.011531,8.575188,6.313070,6.731794,5.626071,7.599191,10.526509,...,4.950081,5.783598,8.166284,6.542631,11.568588,6.480748,7.166575,7.261155,6.629125,7.329671
99,5.314907,9.412282,6.802852,6.691367,8.725342,6.453880,6.432914,5.268741,7.555632,10.866228,...,5.380030,5.750328,8.481860,6.422398,11.750029,5.998599,6.934174,7.430645,6.472826,7.117383
100,5.122138,8.585935,5.408243,6.208525,8.632417,6.294450,6.241890,4.756788,7.724091,10.473209,...,5.333710,5.524866,8.422069,6.667935,11.233422,6.360090,7.016039,7.482703,6.274429,7.161948
102,7.627570,10.466495,7.145158,6.720853,8.220224,5.770071,5.659123,4.839310,7.387862,10.103301,...,5.090540,6.096323,8.037810,6.313436,10.860994,6.396771,6.384832,7.353711,6.135143,8.407977
103,7.955853,10.819812,6.944121,6.673288,8.420866,7.114554,5.547539,4.603229,7.381828,10.546528,...,5.486444,5.740512,8.239966,5.373603,11.405700,7.060555,6.369889,6.878100,5.898187,8.865826
104,5.693186,9.404839,6.274230,6.874047,8.502617,6.928264,6.040774,5.106277,7.543535,10.352518,...,5.735327,5.744890,8.113487,6.080807,11.160590,6.031558,6.224447,6.959109,6.206883,7.218975
105,6.310880,8.885510,5.496766,6.277144,8.693856,6.266459,6.560076,4.699263,7.548922,10.323730,...,5.101234,5.746839,8.045110,6.441394,11.061871,6.018327,6.932191,7.210087,6.082888,7.630631
106,8.569783,10.082934,6.956939,6.217452,8.361501,6.678818,5.481412,5.208927,7.330505,10.390190,...,4.481267,4.923829,7.932829,6.452610,11.162328,6.704416,6.541976,7.277548,6.463910,7.480354
107,7.864217,9.747381,7.556782,6.185464,8.298438,6.734452,6.050321,4.551104,7.627359,10.695776,...,4.462294,6.432629,8.147495,6.676747,11.599388,6.475753,6.723586,7.283561,6.698274,7.491436
108,6.282310,9.222841,6.909221,6.501922,8.658447,6.990535,6.606734,5.475850,8.035822,10.728295,...,5.109122,6.025239,8.176866,6.378735,11.538330,6.618993,6.665933,7.082735,6.260624,7.145249
109,7.741528,9.767630,8.084792,6.883169,8.538317,6.841784,5.561937,5.401876,7.884989,10.527448,...,4.855850,6.153236,8.093101,6.254974,11.250346,6.847408,6.419379,7.173317,6.340819,8.127184
110,7.208186,10.477101,8.349206,6.435280,8.405286,6.477993,6.222579,5.377526,7.336899,10.592849,...,5.332350,6.351906,8.094115,6.513131,11.264208,6.744646,6.596932,7.424511,6.282896,7.878817
111,8.306736,9.728119,6.775051,6.051144,8.445201,5.589521,6.822756,5.231340,7.557992,10.424187,...,4.357925,6.223915,8.041429,6.579247,11.209362,6.601263,7.118868,7.416274,6.467984,8.206853
112,6.644260,8.943801,5.751592,6.175363,9.034463,6.583648,7.155931,3.997030,8.124421,10.851749,...,4.896814,6.065484,8.425812,6.548230,11.826282,7.019724,7.065120,7.617666,6.666629,8.216950
113,8.267494,10.214768,7.094109,6.449796,9.344018,6.692915,6.852810,4.392839,8.301789,11.063934,...,4.954117,6.097556,8.664042,6.706213,12.011318,7.032101,7.486706,8.012881,6.417905,6.490211
114,7.151585,9.911656,6.551207,5.566949,8.442836,6.263887,6.988423,4.881449,8.114867,10.590896,...,4.541595,6.117302,8.005226,6.719635,11.368064,6.758263,7.166976,7.747582,6.503439,6.938745
115,4.994847,8.443938,4.948666,6.301536,9.493595,6.404159,7.493095,4.608845,8.244121,10.718713,...,4.823520,6.468714,8.218384,6.845804,11.321370,6.923316,7.370356,8.092255,6.714039,7.316779
116,4.338852,9.044296,5.622471,5.521820,9.170316,5.875200,7.655159,4.462151,7.570182,10.663976,...,4.331311,6.360366,8.075789,6.744444,11.699924,6.763186,7.181033,7.766562,6.045716,6.079879
117,5.980252,8.355356,5.530052,6.148853,9.371036,6.106453,7.643820,4.558837,8.141417,10.548282,...,4.580055,6.276096,8.134801,6.794351,11.749354,6.643275,7.471708,7.807413,5.794255,7.203309
118,4.505612,9.068354,5.680105,5.924767,9.111874,5.994998,7.484517,5.028569,8.188703,10.491352,...,4.536550,6.570117,8.190575,6.601538,11.486202,6.725646,7.077211,7.637386,5.752789,7.075426
119,5.597460,8.650865,5.218758,6.098022,8.954740,6.008211,6.921282,4.969832,8.161505,10.547830,...,5.100667,6.320683,8.226219,6.647962,11.257406,7.089435,7.223886,7.881830,6.285191,8.027823
120,5.262629,9.384928,5.569193,6.282953,9.233955,5.305219,7.253309,5.017717,7.994534,10.797872,...,4.556950,5.897035,8.059128,6.273490,11.631668,6.974070,6.917432,7.644368,6.217126,8.425275
121,6.704747,9.342444,7.116157,6.325109,8.683595,6.618591,6.048001,4.356982,7.564401,10.729731,...,3.949077,6.187077,7.948759,6.733788,11.687061,7.142842,6.999515,7.503110,6.038225,7.383670
123,6.183570,8.897443,5.423118,6.165506,8.771354,6.669565,6.723326,3.965618,7.766734,10.483695,...,4.746259,6.210221,8.334738,6.569641,11.700565,7.084000,6.965750,7.592950,6.622491,6.321515
124,6.524432,8.801964,5.728301,6.094483,8.792605,6.551825,6.266755,3.794977,7.816113,10.624137,...,4.118302,6.555965,7.809022,6.418178,11.517586,6.656196,6.952473,7.681695,6.363884,7.712087
125,7.221606,9.661409,5.910598,6.127524,8.167905,6.663643,6.088076,4.413147,7.889583,10.511822,...,4.793906,5.861576,8.026999,6.351632,11.349403,7.080796,6.675759,7.289613,6.423686,7.162502
126,7.729729,10.254603,6.611045,6.351687,8.853575,7.106390,5.726409,4.858737,7.840444,10.861723,...,4.867397,6.352640,8.049990,6.399345,11.685472,7.072438,6.984270,7.355536,6.406275,7.456059
127,7.639362,10.055554,7.510701,6.658526,8.499228,7.214766,6.057110,5.172636,7.556889,10.627288,...,5.038392,6.138728,8.270020,5.956187,11.446111,7.290259,7.016897,7.377202,6.466077,7.660224
128,7.838057,11.002534,8.270118,6.019177,8.675886,7.080274,6.419830,4.956735,7.912806,10.755288,...,4.705193,5.222078,8.452863,6.503428,11.597405,7.373787,7.224233,7.580696,6.058169,7.830959
129,8.077537,10.276252,6.114536,6.263756,8.592278,6.632142,5.617401,3.798185,7.627045,10.475673,...,4.746759,5.820802,8.031175,6.308907,11.535426,6.661593,6.838952,7.384663,5.610963,8.048367
130,7.166143,9.615435,6.836252,5.507424,8.735336,6.767973,6.649041,4.822174,7.817770,10.861289,...,4.078755,5.786654,8.127499,6.688908,11.910107,7.323802,6.889108,7.403089,6.744659,7.426063
131,7.540244,9.095864,6.917348,6.168650,8.682271,6.479260,6.619081,4.656674,7.842086,10.577948,...,3.872740,5.898842,8.187308,6.619353,11.328832,6.578694,6.974518,7.468730,5.825379,7.680205
132,6.883413,8.918684,6.115443,5.905714,8.505625,5.880857,6.616853,4.357334,7.870044,10.711813,...,4.641332,6.335894,8.406277,6.488221,11.888595,6.983108,6.811664,7.398692,5.688082,7.774392
133,6.652773,9.735722,6.582636,6.740266,8.526057,6.889145,6.381015,4.882345,7.936449,10.792375,...,5.115212,5.932930,8.254117,6.109064,11.014488,6.811343,6.878725,7.142403,6.194859,7.970330

Training: Coimbra Dataset | Testing: Lisbon Dataset
This section describes the application of Partial Least Squares Discriminant Analysis (PLS-DA) to evaluate the generalizability of the protein signature across different clinical centers (multicentric validation).

In [8]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import matthews_corrcoef, roc_auc_score
from sklearn.model_selection import StratifiedShuffleSplit

# =================================================================
# DATA PREPARATION (Coimbra as Training | Lisbon as External Test)
# =================================================================
X_train = df_coimbra_dc.copy()
y_train = np.array(y_Coimbra)

X_test = df_Lisbon_dc.copy()
y_test = np.array(y_Lisbon)

y_train_bin = (y_train == "MCI-AD").astype(int)
y_test_bin = (y_test == "MCI-AD").astype(int)

# ======================
# GLOBAL PARAMETERS
# ======================
thresholds = [0.7, 0.8, 0.9]
n_iterations = 20
seeds = range(15)

# STORAGE
all_results = []
feature_counter = {}   # To track frequency of EVERY selected protein
threshold_counter = {} # To track frequency of best thresholds

def stratified_bootstrap(X, y):
    ad_idx = np.where(y == "MCI-AD")[0]
    ct_idx = np.where(y == "MCI-CT")[0]
    ad_sample = np.random.choice(ad_idx, size=len(ad_idx), replace=True)
    ct_sample = np.random.choice(ct_idx, size=len(ct_idx), replace=True)
    indices = np.concatenate([ad_sample, ct_sample])
    np.random.shuffle(indices)
    return X.iloc[indices], y[indices]

# ======================
# SEED LOOP
# ======================
for seed in seeds:
    # Internal CV setup
    cv = StratifiedShuffleSplit(n_splits=5, test_size=0.3, random_state=seed)
    threshold_scores = []

    for t in thresholds:
        fold_scores = []
        for train_idx, val_idx in cv.split(X_train, y_train):
            X_subtrain, y_subtrain = X_train.iloc[train_idx], y_train[train_idx]
            X_val, y_val = X_train.iloc[val_idx], y_train[val_idx]

            # Bootstrap Feature Importance
            feature_names = X_subtrain.columns
            importance_matrix = np.zeros((n_iterations, len(feature_names)))

            for i in range(n_iterations):
                X_boot, y_boot = stratified_bootstrap(X_subtrain, y_subtrain)
                rf = RandomForestClassifier(n_estimators=200, class_weight="balanced", n_jobs=-1, random_state=seed)
                rf.fit(X_boot, y_boot)
                importance_matrix[i] = rf.feature_importances_

            mean_importance = importance_matrix.mean(axis=0)
            ranking_df = pd.DataFrame({"protein": feature_names, "importance": mean_importance}).sort_values("importance", ascending=False)
            ranking_df["importance"] /= ranking_df["importance"].sum()
            ranking_df["cum_importance"] = ranking_df["importance"].cumsum()

            selected_features = ranking_df[ranking_df["cum_importance"] <= t]["protein"]
            if len(selected_features) == 0: selected_features = ranking_df["protein"].iloc[:1]

            rf_fold = RandomForestClassifier(n_estimators=200, class_weight="balanced", random_state=seed)
            rf_fold.fit(X_subtrain[selected_features], y_subtrain)
            y_pred = rf_fold.predict(X_val[selected_features])
            fold_scores.append(matthews_corrcoef(y_val, y_pred))

        threshold_scores.append(np.mean(fold_scores))

    # Best threshold for this seed
    best_threshold = thresholds[np.argmax(threshold_scores)]
    threshold_counter[best_threshold] = threshold_counter.get(best_threshold, 0) + 1
    
    # Final Training for this seed
    importance_matrix_final = np.zeros((n_iterations, len(X_train.columns)))
    for i in range(n_iterations):
        X_boot, y_boot = stratified_bootstrap(X_train, y_train)
        rf = RandomForestClassifier(n_estimators=500, class_weight="balanced", n_jobs=-1, random_state=i)
        rf.fit(X_boot, y_boot)
        importance_matrix_final[i] = rf.feature_importances_

    mean_imp_final = importance_matrix_final.mean(axis=0)
    ranking_final = pd.DataFrame({"protein": X_train.columns, "importance": mean_imp_final}).sort_values("importance", ascending=False)
    ranking_final["importance"] /= ranking_final["importance"].sum()
    ranking_final["cum_importance"] = ranking_final["importance"].cumsum()

    top_features = ranking_final[ranking_final["cum_importance"] <= best_threshold]["protein"]
    
    # TRACK EVERY FEATURE SELECTED IN THIS SEED
    for f in top_features:
        feature_counter[f] = feature_counter.get(f, 0) + 1

    # External Test (Lisbon)
    rf_final = RandomForestClassifier(n_estimators=500, class_weight="balanced", random_state=42)
    rf_final.fit(X_train[top_features], y_train)
    y_pred_lisbon = rf_final.predict(X_test[top_features])
    ad_idx_label = np.where(rf_final.classes_ == "MCI-AD")[0][0]
    y_prob_lisbon = rf_final.predict_proba(X_test[top_features])[:, ad_idx_label]

    seed_mcc = matthews_corrcoef(y_test, y_pred_lisbon)
    seed_auc = roc_auc_score(y_test_bin, y_prob_lisbon)

    # PER-SEED REPORT
    print(f"\n>> SEED {seed} RESULTS:")
    print(f"   Best Threshold: {best_threshold}")
    print(f"   Features Selected: {len(top_features)}")
    print(f"   Test MCC: {seed_mcc:.3f}")
    print(f"   Test AUC: {seed_auc:.3f}")

    all_results.append({
        "model": "RF","seed": seed, "mcc": seed_mcc, "auc": seed_auc, 
        "n_features": len(top_features), "threshold": best_threshold
    })

# ======================
# FINAL AGGREGATED REPORT
# ======================
df_res = pd.DataFrame(all_results)

print("\n" + "="*30)
print("FINAL SUMMARY (OVER ALL SEEDS)")
print("="*30)
print(f"Global Mean MCC: {df_res['mcc'].mean():.3f} (±{df_res['mcc'].std():.3f})")
print(f"Global Mean AUC: {df_res['auc'].mean():.3f} (±{df_res['auc'].std():.3f})")
print(f"Avg Features Selected: {df_res['n_features'].mean():.1f}")

print("\n--- Feature Frequency (Top 20) ---")
# Normalized frequency (0.0 to 1.0)
feat_freq_CoimbraonLisbon = (pd.Series(feature_counter).sort_values(ascending=False) / len(seeds))
print(feat_freq_CoimbraonLisbon.head(20))

print("\n--- Threshold Frequency ---")
thresh_freq = (pd.Series(threshold_counter).sort_index() / len(seeds))
print(thresh_freq)

>> SEED 0 RESULTS:
   Best Threshold: 0.7
   Features Selected: 33
   Test MCC: 0.380
   Test AUC: 0.724

>> SEED 1 RESULTS:
   Best Threshold: 0.8
   Features Selected: 49
   Test MCC: 0.380
   Test AUC: 0.776

>> SEED 2 RESULTS:
   Best Threshold: 0.7
   Features Selected: 34
   Test MCC: 0.380
   Test AUC: 0.727

>> SEED 3 RESULTS:
   Best Threshold: 0.8
   Features Selected: 49
   Test MCC: 0.364
   Test AUC: 0.718

>> SEED 4 RESULTS:
   Best Threshold: 0.8
   Features Selected: 51
   Test MCC: 0.380
   Test AUC: 0.693

>> SEED 5 RESULTS:
   Best Threshold: 0.7
   Features Selected: 33
   Test MCC: 0.397
   Test AUC: 0.738

>> SEED 6 RESULTS:
   Best Threshold: 0.8
   Features Selected: 50
   Test MCC: 0.380
   Test AUC: 0.749

>> SEED 7 RESULTS:
   Best Threshold: 0.8
   Features Selected: 49
   Test MCC: 0.380
   Test AUC: 0.692

>> SEED 8 RESULTS:
   Best Threshold: 0.9
   Features Selected: 83
   Test MCC: 0.364
   Test AUC: 0.798

>> SEED 9 RESULTS:
   Best Threshold: 0.8
   Features Selected: 50
   Test MCC: 0.380
   Test AUC: 0.752

>> SEED 10 RESULTS:
   Best Threshold: 0.7
   Features Selected: 32
   Test MCC: 0.380
   Test AUC: 0.728

>> SEED 11 RESULTS:
   Best Threshold: 0.8
   Features Selected: 50
   Test MCC: 0.380
   Test AUC: 0.746

>> SEED 12 RESULTS:
   Best Threshold: 0.8
   Features Selected: 51
   Test MCC: 0.397
   Test AUC: 0.698

>> SEED 13 RESULTS:
   Best Threshold: 0.7
   Features Selected: 32
   Test MCC: 0.380
   Test AUC: 0.732

>> SEED 14 RESULTS:
   Best Threshold: 0.8
   Features Selected: 49
   Test MCC: 0.380
   Test AUC: 0.713

==============================
FINAL SUMMARY (OVER ALL SEEDS)
==============================
Global Mean MCC: 0.380 (±0.009)
Global Mean AUC: 0.732 (±0.029)
Avg Features Selected: 46.3

--- Feature Frequency (Top 20) ---
P61916    1.0
P39060    1.0
P36222    1.0
P01033    1.0
P02751    1.0
P04180    1.0
P54764    1.0
P08123    1.0
Q14982    1.0
Q14118    1.0
Q13449    1.0
P33908    1.0
P01023    1.0
P41222    1.0
Q9UBX5    1.0
P14618    1.0
P23142    1.0
Q92876    1.0
P02766    1.0
Q16270    1.0
dtype: float64

--- Threshold Frequency ---
0.7    0.333333
0.8    0.600000
0.9    0.066667
dtype: float64

Dataset: Coimbra + Lisbon (Merged)
In this section, a Partial Least Squares Discriminant Analysis (Random Forest) is performed on the combined clinical proteomic dataset.

In [9]:
print(len(feat_freq_CoimbraonLisbon))
feat_freq_CoimbraonLisbon.to_pickle('feat_freq_CoimbraonLisbon_rf_threshold.pkl')
df_res.to_pickle('results_CoimbraonLisbon_rf_threshold.pkl')

83

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import matthews_corrcoef, roc_auc_score

# ======================
# DATI
# ======================
X = data_log2.copy()
y = np.array(list_groups)

# binarizza per AUC (importante!)
y_binary = (y == "MCI-AD").astype(int)

# ======================
# PARAMETRI GLOBALI
# ======================
thresholds = [ 0.7, 0.8, 0.9]
n_iterations = 20
seeds = range(15)

# ======================
# STORAGE
# ======================
all_results = []
feature_counter = {}
threshold_counter = {}

# ======================
# BOOTSTRAP
# ======================
def stratified_bootstrap(X, y):
    ad_idx = np.where(y == "MCI-AD")[0]
    ct_idx = np.where(y == "MCI-CT")[0]

    ad_sample = np.random.choice(ad_idx, size=len(ad_idx), replace=True)
    ct_sample = np.random.choice(ct_idx, size=len(ct_idx), replace=True)

    indices = np.concatenate([ad_sample, ct_sample])
    np.random.shuffle(indices)

    return X.iloc[indices], y[indices]


# ======================
# LOOP SEED
# ======================
for seed in seeds:

    print(f"\n===== SEED {seed} =====")

    # Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        stratify=y,
        random_state=seed
    )

    y_train_bin = (y_train == "MCI-AD").astype(int)
    y_test_bin = (y_test == "MCI-AD").astype(int)

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)

    threshold_scores = []

    # ======================
    # CV per scegliere threshold
    # ======================
    for t in thresholds:

        fold_scores = []

        for train_idx, val_idx in cv.split(X_train, y_train):

            X_subtrain = X_train.iloc[train_idx]
            y_subtrain = y_train[train_idx]

            X_val = X_train.iloc[val_idx]
            y_val = y_train[val_idx]

            y_val_bin = (y_val == "MCI-AD").astype(int)

            # ===== bootstrap importance
            feature_names = X_subtrain.columns
            importance_matrix = np.zeros((n_iterations, len(feature_names)))

            for i in range(n_iterations):

                X_boot, y_boot = stratified_bootstrap(X_subtrain, y_subtrain)

                rf = RandomForestClassifier(
                    n_estimators=200,
                    class_weight="balanced",
                    n_jobs=-1,
                    random_state=seed
                )

                rf.fit(X_boot, y_boot)
                importance_matrix[i] = rf.feature_importances_

            mean_importance = importance_matrix.mean(axis=0)

            ranking_df = pd.DataFrame({
                "protein": feature_names,
                "importance": mean_importance
            }).sort_values("importance", ascending=False)

            # normalizzazione
            ranking_df["importance"] /= ranking_df["importance"].sum()
            ranking_df["cum_importance"] = ranking_df["importance"].cumsum()

            # selezione feature
            selected_features = ranking_df[
                ranking_df["cum_importance"] <= t
            ]["protein"]

            if len(selected_features) == 0:
                selected_features = ranking_df["protein"].iloc[:1]

            # train modello
            rf = RandomForestClassifier(
                n_estimators=200,
                class_weight="balanced",
                random_state=seed
            )

            rf.fit(X_subtrain[selected_features], y_subtrain)

            # valutazione
            y_pred = rf.predict(X_val[selected_features])
            mcc = matthews_corrcoef(y_val, y_pred)

            fold_scores.append(mcc)

        threshold_scores.append(np.mean(fold_scores))

    # ======================
    # best threshold
    # ======================
    best_threshold = thresholds[np.argmax(threshold_scores)]
    print("Best threshold:", best_threshold)

    # ======================
    # TRAIN FINALE (su tutto train)
    # ======================
    feature_names = X_train.columns
    importance_matrix = np.zeros((n_iterations, len(feature_names)))

    for i in range(n_iterations):

        X_boot, y_boot = stratified_bootstrap(X_train, y_train)

        rf = RandomForestClassifier(
            n_estimators=500,
            class_weight="balanced",
            n_jobs=-1,
            random_state=i
        )

        rf.fit(X_boot, y_boot)
        importance_matrix[i] = rf.feature_importances_

    mean_importance = importance_matrix.mean(axis=0)

    ranking_df = pd.DataFrame({
        "protein": feature_names,
        "importance": mean_importance
    }).sort_values("importance", ascending=False)

    ranking_df["importance"] /= ranking_df["importance"].sum()
    ranking_df["cum_importance"] = ranking_df["importance"].cumsum()

    top_features = ranking_df[
        ranking_df["cum_importance"] <= best_threshold
    ]["protein"]

    if len(top_features) == 0:
        top_features = ranking_df["protein"].iloc[:1]

    print("Numero feature:", len(top_features))

    # ======================
    # TEST
    # ======================
    rf_final = RandomForestClassifier(
        n_estimators=500,
        class_weight="balanced",
        random_state=42
    )

    rf_final.fit(X_train[top_features], y_train)

    y_pred = rf_final.predict(X_test[top_features])
    class_order = rf_final.classes_
    ad_index = np.where(class_order == "MCI-AD")[0][0]
    
    y_prob = rf_final.predict_proba(X_test[top_features])[:, ad_index]

    test_mcc = matthews_corrcoef(y_test, y_pred)
    test_auc = roc_auc_score(y_test_bin, y_prob)
    print("Class order:", rf_final.classes_)
    print("Test MCC:", test_mcc)
    print("Test AUC:", test_auc)

    # ======================
    # SALVATAGGIO
    # ======================
    all_results.append({
        "seed": seed,
        "mcc": test_mcc,
        "auc": test_auc,
        "n_features": len(top_features),
        "best_threshold": best_threshold
    })

    # frequenza feature
    for f in top_features:
        feature_counter[f] = feature_counter.get(f, 0) + 1

    # frequenza threshold
    threshold_counter[best_threshold] = threshold_counter.get(best_threshold, 0) + 1


# ======================
# RISULTATI FINALI
# ======================
df_results = pd.DataFrame(all_results)

print("\n===== FINAL RESULTS =====")
print("Mean MCC:", df_results["mcc"].mean())
print("Mean AUC:", df_results["auc"].mean())

# frequenze
feature_freq = pd.Series(feature_counter).sort_values(ascending=False) / len(seeds)
threshold_freq = pd.Series(threshold_counter).sort_index() / len(seeds)

print("\nTop features (frequency):")
print(feature_freq.head(20))

print("\nThreshold frequency:")
print(threshold_freq)

===== SEED 0 =====
Best threshold: 0.8
Numero feature: 81
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.9225998461903602
Test AUC: 1.0

===== SEED 1 =====
Best threshold: 0.9
Numero feature: 122
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.9230769230769231
Test AUC: 0.9807692307692308

===== SEED 2 =====
Best threshold: 0.8
Numero feature: 75
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.761306166786451
Test AUC: 0.9871794871794872

===== SEED 3 =====
Best threshold: 0.9
Numero feature: 127
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.9230769230769231
Test AUC: 0.9615384615384616

===== SEED 4 =====
Best threshold: 0.8
Numero feature: 78
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.9225998461903602
Test AUC: 1.0

===== SEED 5 =====
Best threshold: 0.8
Numero feature: 84
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.8498365855987975
Test AUC: 1.0

===== SEED 6 =====
Best threshold: 0.8
Numero feature: 78
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.8498365855987975
Test AUC: 1.0

===== SEED 7 =====
Best threshold: 0.7
Numero feature: 48
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.9225998461903602
Test AUC: 1.0

===== SEED 8 =====
Best threshold: 0.9
Numero feature: 128
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 1.0
Test AUC: 1.0

===== SEED 9 =====
Best threshold: 0.7
Numero feature: 52
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 1.0
Test AUC: 1.0

===== SEED 10 =====
Best threshold: 0.8
Numero feature: 82
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.9230769230769231
Test AUC: 0.9935897435897435

===== SEED 11 =====
Best threshold: 0.9
Numero feature: 128
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 0.9225998461903602
Test AUC: 1.0

===== SEED 12 =====
Best threshold: 0.7
Numero feature: 53
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 1.0
Test AUC: 1.0

===== SEED 13 =====
Best threshold: 0.8
Numero feature: 80
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 1.0
Test AUC: 1.0

===== SEED 14 =====
Best threshold: 0.9
Numero feature: 123
Class order: ['MCI-AD' 'MCI-CT']
Test MCC: 1.0
Test AUC: 1.0

===== FINAL RESULTS =====
Mean MCC: 0.9280406327984171
Mean AUC: 0.9948717948717948

Top features (frequency):
P14618    1.0
P07998    1.0
P16035    1.0
P51693    1.0
P05546    1.0
P09871    1.0
P05067    1.0
P23142    1.0
Q12860    1.0
Q9NT99    1.0
Q92876    1.0
Q15582    1.0
O00533    1.0
P54289    1.0
P12109    1.0
P01024    1.0
P27169    1.0
P07195    1.0
P08294    1.0
Q9NQ79    1.0
dtype: float64

Threshold frequency:
0.7    0.200000
0.8    0.466667
0.9    0.333333
dtype: float64

In [11]:
print(len(feature_freq))
feature_freq.to_pickle('feature_freq_LC_rf_threshold.pkl')
df_results = pd.DataFrame(all_results)
df_results.to_pickle('results_LC_rf_threshold.pkl')

157

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import matthews_corrcoef, roc_auc_score

# ======================
# DATI
# ======================
X = data_log2.copy()
y = np.array(list_groups)
y_binary = (y == "MCI-AD").astype(int)

# ======================
# PARAMETRI
# ======================
thresholds = [0.7, 0.8, 0.9]
n_iterations = 20
n_splits = 5

# ======================
# BOOTSTRAP
# ======================
def stratified_bootstrap(X, y):
    ad_idx = np.where(y == "MCI-AD")[0]
    ct_idx = np.where(y == "MCI-CT")[0]

    ad_sample = np.random.choice(ad_idx, size=len(ad_idx), replace=True)
    ct_sample = np.random.choice(ct_idx, size=len(ct_idx), replace=True)

    indices = np.concatenate([ad_sample, ct_sample])
    np.random.shuffle(indices)

    return X.iloc[indices], y[indices]

# ======================
# CV
# ======================
cv = StratifiedShuffleSplit(n_splits=n_splits, test_size=0.3, random_state=42)

threshold_scores = []

# ======================
# SCELTA THRESHOLD (CV)
# ======================
for t in thresholds:

    fold_mcc = []
    fold_auc = []

    for train_idx, val_idx in cv.split(X, y):

        X_sub = X.iloc[train_idx]
        y_sub = y[train_idx]

        X_val = X.iloc[val_idx]
        y_val = y[val_idx]
        y_val_bin = (y_val == "MCI-AD").astype(int)

        # ===== bootstrap importance
        feature_names = X_sub.columns
        importance_matrix = np.zeros((n_iterations, len(feature_names)))

        for i in range(n_iterations):
            X_boot, y_boot = stratified_bootstrap(X_sub, y_sub)

            rf = RandomForestClassifier(
                n_estimators=200,
                class_weight="balanced",
                n_jobs=-1,
                random_state=i
            )

            rf.fit(X_boot, y_boot)
            importance_matrix[i] = rf.feature_importances_

        mean_importance = importance_matrix.mean(axis=0)

        ranking_df = pd.DataFrame({
            "protein": feature_names,
            "importance": mean_importance
        }).sort_values("importance", ascending=False)

        ranking_df["importance"] /= ranking_df["importance"].sum()
        ranking_df["cum_importance"] = ranking_df["importance"].cumsum()

        selected_features = ranking_df[
            ranking_df["cum_importance"] <= t
        ]["protein"]

        if len(selected_features) == 0:
            selected_features = ranking_df["protein"].iloc[:1]

        # modello
        rf_model = RandomForestClassifier(
            n_estimators=200,
            class_weight="balanced",
            random_state=42
        )

        rf_model.fit(X_sub[selected_features], y_sub)

        y_pred = rf_model.predict(X_val[selected_features])

        # ✅ FIX AUC
        class_order = rf_model.classes_
        ad_index = np.where(class_order == "MCI-AD")[0][0]
        y_prob = rf_model.predict_proba(X_val[selected_features])[:, ad_index]

        fold_mcc.append(matthews_corrcoef(y_val, y_pred))
        fold_auc.append(roc_auc_score(y_val_bin, y_prob))

    threshold_scores.append(np.mean(fold_mcc))

# ======================
# BEST THRESHOLD
# ======================
best_threshold = thresholds[np.argmax(threshold_scores)]
print("Best threshold:", best_threshold)

# ======================
# PERFORMANCE FINALE (CV)
# ======================
all_mcc = []
all_auc = []

# ✅ FREQUENZA FEATURE
feature_counts = pd.Series(0, index=X.columns)

for train_idx, val_idx in cv.split(X, y):

    X_sub = X.iloc[train_idx]
    y_sub = y[train_idx]

    X_val = X.iloc[val_idx]
    y_val = y[val_idx]
    y_val_bin = (y_val == "MCI-AD").astype(int)

    # bootstrap importance
    importance_matrix = np.zeros((n_iterations, X.shape[1]))

    for i in range(n_iterations):
        X_boot, y_boot = stratified_bootstrap(X_sub, y_sub)

        rf = RandomForestClassifier(
            n_estimators=200,
            class_weight="balanced",
            n_jobs=-1,
            random_state=i
        )

        rf.fit(X_boot, y_boot)
        importance_matrix[i] = rf.feature_importances_

    mean_importance = importance_matrix.mean(axis=0)

    ranking_df = pd.DataFrame({
        "protein": X.columns,
        "importance": mean_importance
    }).sort_values("importance", ascending=False)

    ranking_df["importance"] /= ranking_df["importance"].sum()
    ranking_df["cum_importance"] = ranking_df["importance"].cumsum()

    selected_features = ranking_df[
        ranking_df["cum_importance"] <= best_threshold
    ]["protein"]

    if len(selected_features) == 0:
        selected_features = ranking_df["protein"].iloc[:1]

    # ✅ conteggio frequenza
    feature_counts[selected_features] += 1

    rf_model = RandomForestClassifier(
        n_estimators=200,
        class_weight="balanced",
        random_state=42
    )

    rf_model.fit(X_sub[selected_features], y_sub)

    y_pred = rf_model.predict(X_val[selected_features])

    # ✅ FIX AUC
    class_order = rf_model.classes_
    ad_index = np.where(class_order == "MCI-AD")[0][0]
    y_prob = rf_model.predict_proba(X_val[selected_features])[:, ad_index]

    all_mcc.append(matthews_corrcoef(y_val, y_pred))
    all_auc.append(roc_auc_score(y_val_bin, y_prob))

# ======================
# METRICHE FINALI
# ======================
print("\n=== VALIDATION PERFORMANCE ===")
print(f"MCC: {np.mean(all_mcc):.4f} ± {np.std(all_mcc):.4f}")
print(f"AUC: {np.mean(all_auc):.4f} ± {np.std(all_auc):.4f}")

# ======================
# FREQUENZA FEATURE
# ======================
feature_freq = (feature_counts / n_splits).sort_values(ascending=False)

print("\n=== FEATURE SELECTION FREQUENCY ===")
print(feature_freq)

# ======================
# FEATURE IMPORTANCE FINALE
# ======================
importance_matrix = np.zeros((n_iterations, X.shape[1]))

for i in range(n_iterations):
    X_boot, y_boot = stratified_bootstrap(X, y)

    rf = RandomForestClassifier(
        n_estimators=500,
        class_weight="balanced",
        n_jobs=-1,
        random_state=i
    )

    rf.fit(X_boot, y_boot)
    importance_matrix[i] = rf.feature_importances_

mean_importance = importance_matrix.mean(axis=0)

ranking_df = pd.DataFrame({
    "protein": X.columns,
    "importance": mean_importance
}).sort_values("importance", ascending=False)

ranking_df["importance"] /= ranking_df["importance"].sum()
ranking_df["cum_importance"] = ranking_df["importance"].cumsum()

print("\n=== GLOBAL RF RANKING ===")
print(ranking_df)

# salva
ranking_df.to_csv("rf_global_ranking.csv", index=False)
feature_freq.to_csv("rf_feature_frequency.csv")

Best threshold: 0.8

=== VALIDATION PERFORMANCE ===
MCC: 0.9062 ± 0.0213
AUC: 0.9789 ± 0.0113

=== FEATURE SELECTION FREQUENCY ===
Protein.Group
P40925    1.0
P14618    1.0
P23142    1.0
P02647    1.0
Q86UX2    1.0
         ...
P05452    0.0
P05154    0.0
P04264    0.0
P04217    0.0
P10451    0.0
Length: 201, dtype: float64

=== GLOBAL RF RANKING ===
    protein  importance  cum_importance
110  P14618    0.077021        0.077021
55   P02766    0.042323        0.119344
127  P25311    0.041901        0.161245
158  Q13449    0.038572        0.199817
168  Q16270    0.038223        0.238040
..      ...         ...             ...
18   P00748    0.000766        0.997206
26   P01031    0.000743        0.997949
60   P04004    0.000721        0.998671
95   P08697    0.000694        0.999364
56   P02768    0.000636        1.000000

[201 rows x 3 columns]

In [13]:
feature_freq.to_pickle('feature_2_rf_LC_threshold.pkl')

Training: Lisbon Dataset | Testing: Coimbra Dataset
This section describes the "Inverse Validation" approach using Partial Least Squares Discriminant Analysis (PLS-DA). By swapping the roles of the two cohorts, we test the consistency and symmetry of our protein biomarkers.

In [14]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import matthews_corrcoef, roc_auc_score
from sklearn.model_selection import StratifiedShuffleSplit

# =================================================================
# DATA PREPARATION (Lisbon as Training | Coimbra as External Test)
# =================================================================
print('ok')
X_train = df_Lisbon_dc.copy()
y_train = np.array(y_Lisbon)

X_test = df_coimbra_dc.copy()
y_test = np.array(y_Coimbra)

y_train_bin = (y_train == "MCI-AD").astype(int)
y_test_bin = (y_test == "MCI-AD").astype(int)

# ======================
# GLOBAL PARAMETERS
# ======================
thresholds = [0.7, 0.8, 0.9]
n_iterations = 20
seeds = range(15)

# STORAGE
all_results = []
feature_counter = {}   # To track frequency of EVERY selected protein
threshold_counter = {} # To track frequency of best thresholds

def stratified_bootstrap(X, y):
    ad_idx = np.where(y == "MCI-AD")[0]
    ct_idx = np.where(y == "MCI-CT")[0]
    ad_sample = np.random.choice(ad_idx, size=len(ad_idx), replace=True)
    ct_sample = np.random.choice(ct_idx, size=len(ct_idx), replace=True)
    indices = np.concatenate([ad_sample, ct_sample])
    np.random.shuffle(indices)
    return X.iloc[indices], y[indices]

# ======================
# SEED LOOP
# ======================
for seed in seeds:
    # Internal CV setup
    cv = StratifiedShuffleSplit(n_splits=5, test_size=0.3, random_state=seed)
    threshold_scores = []

    for t in thresholds:
        fold_scores = []
        for train_idx, val_idx in cv.split(X_train, y_train):
            X_subtrain, y_subtrain = X_train.iloc[train_idx], y_train[train_idx]
            X_val, y_val = X_train.iloc[val_idx], y_train[val_idx]

            # Bootstrap Feature Importance
            feature_names = X_subtrain.columns
            importance_matrix = np.zeros((n_iterations, len(feature_names)))

            for i in range(n_iterations):
                X_boot, y_boot = stratified_bootstrap(X_subtrain, y_subtrain)
                rf = RandomForestClassifier(n_estimators=200, class_weight="balanced", n_jobs=-1, random_state=seed)
                rf.fit(X_boot, y_boot)
                importance_matrix[i] = rf.feature_importances_

            mean_importance = importance_matrix.mean(axis=0)
            ranking_df = pd.DataFrame({"protein": feature_names, "importance": mean_importance}).sort_values("importance", ascending=False)
            ranking_df["importance"] /= ranking_df["importance"].sum()
            ranking_df["cum_importance"] = ranking_df["importance"].cumsum()

            selected_features = ranking_df[ranking_df["cum_importance"] <= t]["protein"]
            if len(selected_features) == 0: selected_features = ranking_df["protein"].iloc[:1]

            rf_fold = RandomForestClassifier(n_estimators=200, class_weight="balanced", random_state=seed)
            rf_fold.fit(X_subtrain[selected_features], y_subtrain)
            y_pred = rf_fold.predict(X_val[selected_features])
            fold_scores.append(matthews_corrcoef(y_val, y_pred))

        threshold_scores.append(np.mean(fold_scores))

    # Best threshold for this seed
    best_threshold = thresholds[np.argmax(threshold_scores)]
    threshold_counter[best_threshold] = threshold_counter.get(best_threshold, 0) + 1
    
    # Final Training for this seed
    importance_matrix_final = np.zeros((n_iterations, len(X_train.columns)))
    for i in range(n_iterations):
        X_boot, y_boot = stratified_bootstrap(X_train, y_train)
        rf = RandomForestClassifier(n_estimators=500, class_weight="balanced", n_jobs=-1, random_state=i)
        rf.fit(X_boot, y_boot)
        importance_matrix_final[i] = rf.feature_importances_

    mean_imp_final = importance_matrix_final.mean(axis=0)
    ranking_final = pd.DataFrame({"protein": X_train.columns, "importance": mean_imp_final}).sort_values("importance", ascending=False)
    ranking_final["importance"] /= ranking_final["importance"].sum()
    ranking_final["cum_importance"] = ranking_final["importance"].cumsum()

    top_features = ranking_final[ranking_final["cum_importance"] <= best_threshold]["protein"]
    
    # TRACK EVERY FEATURE SELECTED IN THIS SEED
    for f in top_features:
        feature_counter[f] = feature_counter.get(f, 0) + 1

    # External Test (Lisbon)
    rf_final = RandomForestClassifier(n_estimators=500, class_weight="balanced", random_state=42)
    rf_final.fit(X_train[top_features], y_train)
    y_pred_lisbon = rf_final.predict(X_test[top_features])
    ad_idx_label = np.where(rf_final.classes_ == "MCI-AD")[0][0]
    y_prob_lisbon = rf_final.predict_proba(X_test[top_features])[:, ad_idx_label]

    seed_mcc = matthews_corrcoef(y_test, y_pred_lisbon)
    seed_auc = roc_auc_score(y_test_bin, y_prob_lisbon)

    # PER-SEED REPORT
    print(f"\n>> SEED {seed} RESULTS:")
    print(f"   Best Threshold: {best_threshold}")
    print(f"   Features Selected: {len(top_features)}")
    print(f"   Test MCC: {seed_mcc:.3f}")
    print(f"   Test AUC: {seed_auc:.3f}")

    all_results.append({
        "seed": seed, "mcc": seed_mcc, "auc": seed_auc, 
        "n_features": len(top_features), "threshold": best_threshold
    })

# ======================
# FINAL AGGREGATED REPORT
# ======================
df_res = pd.DataFrame(all_results)

print("\n" + "="*30)
print("FINAL SUMMARY (OVER ALL SEEDS)")
print("="*30)
print(f"Global Mean MCC: {df_res['mcc'].mean():.3f} (±{df_res['mcc'].std():.3f})")
print(f"Global Mean AUC: {df_res['auc'].mean():.3f} (±{df_res['auc'].std():.3f})")
print(f"Avg Features Selected: {df_res['n_features'].mean():.1f}")

print("\n--- Feature Frequency (Top 20) ---")
# Normalized frequency (0.0 to 1.0)
feat_freq_LisbononCoimbra = (pd.Series(feature_counter).sort_values(ascending=False) / len(seeds))
print(feat_freq_LisbononCoimbra.head(20))

print("\n--- Threshold Frequency ---")
thresh_freq = (pd.Series(threshold_counter).sort_index() / len(seeds))
print(thresh_freq)

ok

>> SEED 0 RESULTS:
   Best Threshold: 0.7
   Features Selected: 49
   Test MCC: 0.752
   Test AUC: 0.985

>> SEED 1 RESULTS:
   Best Threshold: 0.7
   Features Selected: 51
   Test MCC: 0.726
   Test AUC: 0.984

>> SEED 2 RESULTS:
   Best Threshold: 0.7
   Features Selected: 52
   Test MCC: 0.807
   Test AUC: 0.972

>> SEED 3 RESULTS:
   Best Threshold: 0.7
   Features Selected: 49
   Test MCC: 0.866
   Test AUC: 0.988

>> SEED 4 RESULTS:
   Best Threshold: 0.8
   Features Selected: 79
   Test MCC: 0.701
   Test AUC: 1.000

>> SEED 5 RESULTS:
   Best Threshold: 0.7
   Features Selected: 51
   Test MCC: 0.836
   Test AUC: 0.986

>> SEED 6 RESULTS:
   Best Threshold: 0.7
   Features Selected: 51
   Test MCC: 0.836
   Test AUC: 0.982

>> SEED 7 RESULTS:
   Best Threshold: 0.7
   Features Selected: 52
   Test MCC: 0.701
   Test AUC: 0.983

>> SEED 8 RESULTS:
   Best Threshold: 0.8
   Features Selected: 82
   Test MCC: 0.701
   Test AUC: 0.991

>> SEED 9 RESULTS:
   Best Threshold: 0.8
   Features Selected: 83
   Test MCC: 0.779
   Test AUC: 1.000

>> SEED 10 RESULTS:
   Best Threshold: 0.7
   Features Selected: 49
   Test MCC: 0.779
   Test AUC: 0.984

>> SEED 11 RESULTS:
   Best Threshold: 0.9
   Features Selected: 125
   Test MCC: 0.701
   Test AUC: 0.999

>> SEED 12 RESULTS:
   Best Threshold: 0.7
   Features Selected: 52
   Test MCC: 0.779
   Test AUC: 0.984

>> SEED 13 RESULTS:
   Best Threshold: 0.8
   Features Selected: 81
   Test MCC: 0.652
   Test AUC: 0.984

>> SEED 14 RESULTS:
   Best Threshold: 0.8
   Features Selected: 79
   Test MCC: 0.676
   Test AUC: 0.995

==============================
FINAL SUMMARY (OVER ALL SEEDS)
==============================
Global Mean MCC: 0.753 (±0.065)
Global Mean AUC: 0.988 (±0.008)
Avg Features Selected: 65.7

--- Feature Frequency (Top 20) ---
P14618    1.0
P06733    1.0
P01019    1.0
P54764    1.0
P17174    1.0
P02750    1.0
P13473    1.0
P02763    1.0
Q13740    1.0
P05546    1.0
Q86UX2    1.0
O14594    1.0
P40925    1.0
O00533    1.0
P24592    1.0
P01024    1.0
P36222    1.0
P06396    1.0
P51693    1.0
P55058    1.0
dtype: float64

--- Threshold Frequency ---
0.7    0.600000
0.8    0.333333
0.9    0.066667
dtype: float64

In [15]:
print(len(feat_freq_LisbononCoimbra))
feat_freq_LisbononCoimbra.to_pickle('feat_freq_LisbononCoimbra_rf_threshold.pkl')
df_res.to_pickle('results_LisbononCoimbra_rf_threshold.pkl')

126